config/routes.rb
Rails.application.routes.draw do
  with_options controller: :home do
    get '/callback', action: :verify, as: :verify
    post '/callback', action: :callback, as: :callback
    post '/subscribe', action: :subscribe, as: :subscribe
    post '/reload', action: :reload, as: :reload
    root action: :index
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
    @params = params.slice(:left_user, :right_user)
    @left_user = User.find_by(id: @params[:left_user])
    @right_user = User.find_by(id: @params[:right_user])
    get_friends(@left_user)
    get_friends(@right_user)
    @subscriptions = realtime.list_subscriptions
  end

  def reload
    test_users_api = Koala::Facebook::TestUsers.new(credentials)

    user_ids = []
    test_users_api.list.each do |user|
      user_ids << user['id']
      u = User.find_or_initialize_by(fb: user['id'])
      u.update!(token: user['access_token'])
    end

    users = Koala::Facebook::API.new(app_access_token).get_objects(user_ids)
    users.each_value do |user|
      u = User.find_or_initialize_by(fb: user['id'])
      u.update!(name: user['name'])
    end

    redirect_to(action: :index)
  end

  def verify
    # subs_url = Rails.application.routes.url_helpers.subs_url(host: 'http://localhost:3000')
    # ups.subscribe("user", "friends", subs_url, Facebook::SVToken)
    Koala::Facebook::RealtimeUpdates.meet_challenge(params, Facebook::SVToken)
    head :ok
  end

  def subscribe
  end

  private

  def app_access_token
    @app_access_token ||= Koala::Facebook::OAuth.new.get_app_access_token
  end

  def credentials
    @credentials ||= { app_id: Facebook::APP_ID, app_access_token: app_access_token }
  end

  def get_friends(user)
    return unless user && user.token
    api = Koala::Facebook::API.new(user.token)
    user.friends = api.get_connections("me", "friends")
  end

  def realtime
    @realtime ||= Koala::Facebook::RealtimeUpdates.new(credentials)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_user.html.slim
- unless user
  h3 = "Please, select #{side} user"
- else
  - pp user.friends
  h3 = user.name
  p = user.token ? 'Authorized' : 'Not authorized'
  ul.list-group
  - user.friends && user.friends.each do |friend|
    li.list-group-item data-id=friend['id']
      = friend['name']

app/views/home/index.html.slim
.container
  .row
    .col-md-12
      h1.page-header
        ' State
        = link_to('reload data', reload_path, method: :post, class: 'btn btn-primary')
      .well
        = @subscriptions
        a.btn.btn-success href=subscribe_path
      ul.list-group
        - @users.each do |user|
          li.list-group-item data-id=user.id
            .btn-group role='group'
              a.btn.btn-warning href=root_path(@params.merge(left_user: user.id)) class=('active' if user == @left_user)
                = icon('arrow-left')
              a.btn.btn-warning href=root_path(@params.merge(right_user: user.id)) class=('active' if user == @right_user)
                = icon('arrow-right')
            = user.name
            =< icon('check-square-o') if user.token
  .row
    .col-md-12
      | &nbsp;
  .row
    .col-md-5
      = render 'user', user: @left_user, side: 'left'
    .col-md-2
    .col-md-5
      = render 'user', user: @right_user, side: 'right'

app/views/layouts/application.html.slim
doctype html
html lang='ru'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    title FB updates
    == stylesheet_link_tag 'application', media: 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
    /[if lt IE 9]
      script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'
      script src='https://oss.maxcdn.com/respond/1.4.2/respond.min.js'
  body
    == yield